# Generated by Django 5.0.2 on 2025-12-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IotDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'iot_devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IotUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'iot_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IotUserDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.DO_NOTHING, to='iot.iotdevice')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='iot.iotuser')),
            ],
            options={
                'db_table': 'iot_user_devices',
                'managed': True,
            },
        ),
    ]
