# Generated by Django 5.0.2 on 2025-12-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdevice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='iotuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='iotuserdevice',
            options={'managed': False},
        ),
    ]
