# Generated by Django 5.0.2 on 2026-04-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_alter_iotdevice_options_alter_iotuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('requirement', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
