# Generated by Django 5.0.2 on 2026-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
