# Generated by Django 5.0.2 on 2026-01-11 06:02

import ota.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='file',
            field=models.FileField(storage=ota.storage.FirmwareStorage(), upload_to='firmware/'),
        ),
    ]
