# Generated by Django 5.0.2 on 2026-04-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.CharField(help_text='Customer phone number', max_length=10),
        ),
    ]
