# Generated by Django 5.0.2 on 2026-04-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0002_alter_invoice_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_path',
        ),
    ]
