# Generated by Django 5.0.2 on 2026-06-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('current_state', models.CharField(choices=[('start', 'Start'), ('waiting_category', 'Waiting Category Selection'), ('waiting_solar_details', 'Waiting Solar Details'), ('waiting_machine_details', 'Waiting Machine Details'), ('completed', 'Completed')], default='start', max_length=30)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Temporary data collected during flow')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat State',
                'verbose_name_plural': 'Chat States',
                'db_table': 'crm_chat_state',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='http://127.0.0.1:4001', help_text='Baileys Node.js server URL')),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Shared secret for webhook verification', max_length=255)),
                ('connected_phone', models.CharField(blank=True, default='', help_text='WhatsApp number connected via Baileys', max_length=20)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
                'db_table': 'crm_whatsapp_config',
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='message_id',
            field=models.CharField(blank=True, help_text='Baileys message ID for delivery tracking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whatsappconversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LeadTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('followup_added', 'Follow-Up Added'), ('message_received', 'Message Received'), ('message_sent', 'Message Sent'), ('user_assigned', 'User Assigned'), ('category_selected', 'Category Selected'), ('quote_sent', 'Quote Sent'), ('deal_closed', 'Deal Closed'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='CRM.crmuser')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='CRM.lead')),
            ],
            options={
                'verbose_name': 'Lead Timeline',
                'verbose_name_plural': 'Lead Timeline Events',
                'db_table': 'crm_lead_timeline',
                'ordering': ['-created_at'],
            },
        ),
    ]
