# Generated by Django 5.0.2 on 2026-01-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('wash_type', models.CharField(choices=[('BEFORE', 'Before Wash'), ('AFTER', 'After Wash')], max_length=10)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SolarHourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power', models.FloatField()),
                ('energy', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_id', 'timestamp'], name='solar_solar_device__6f7555_idx')],
            },
        ),
    ]
