# Generated by Django 5.0.2 on 2026-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarhourlydata',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarhourlydata',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
