# Generated by Django 5.0.2 on 2026-01-13 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_solarhourlydata_lat_solarhourlydata_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('city', models.CharField(default='Unknown', max_length=200)),
                ('state', models.CharField(default='Unknown', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.RemoveIndex(
            model_name='solarhourlydata',
            name='solar_solar_device__6f7555_idx',
        ),
        migrations.AlterField(
            model_name='solarhourlydata',
            name='device_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='solarhourlydata',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solarhourlydata',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='washrecord',
            name='device_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='washrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='washrecord',
            name='wash_type',
            field=models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='solarhourlydata',
            index=models.Index(fields=['-timestamp', 'device_id'], name='solar_solar_timesta_d5e1f5_idx'),
        ),
    ]
