# Generated by Django 5.0.2 on 2026-01-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_devicelocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarhourlydata',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='solarhourlydata',
            name='lon',
        ),
    ]
