# Generated by Django 5.0.2 on 2026-01-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_remove_solarhourlydata_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
