# Generated by Django 5.0.2 on 2026-01-18 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_alter_devicelocation_lat_alter_devicelocation_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='capacity',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='price',
            field=models.FloatField(default=5.0),
        ),
        migrations.CreateModel(
            name='SolarAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'device_id'], name='solar_solar_timesta_e55ee7_idx')],
            },
        ),
    ]
