# Generated by Django 5.0.2 on 2026-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0006_devicelocation_capacity_devicelocation_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('to_consider', models.CharField(max_length=100)),
            ],
        ),
    ]
