# Generated by Django 5.0.2 on 2026-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0008_weatherlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlog',
            name='max_rain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='skip_wash',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
