# Generated by Django 5.0.2 on 2026-05-24 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_weatherlog_max_rain_weatherlog_skip_wash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'device_id'], name='solar_solar_timesta_57ff13_idx')],
            },
        ),
    ]
